change:
  - head-branch: ["^change/"]

enhancement:
  - head-branch: ["^feature/", "^feat/", "^enhancement/", "^enh/"]

bug:
  - head-branch: ["^fix/", "^bug/"]

chore:
  - head-branch: ["^chore/"]

tests:
  - any:
      - head-branch: ["^tests/", "^test/"]
      - changed-files:
          - any-glob-to-any-file: "tests/**/*"
  - all:
      - changed-files:
          - all-globs-to-all-files: ["!tests/requirements.txt"]

documentation:
  - head-branch: ["^docs/", "^doc/"]
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

dependencies:
  - head-branch:
      ["^deps/", "^dep/", "^dependabot/", "pre-commit-ci-update-config"]
  - changed-files:
      - any-glob-to-any-file: ["go.mod", "go.sum"]
