version: 2
env:
  - CGO_ENABLED=0

before:
  hooks:
    - make LICENSES

builds:
  - id: nginx-asg-sync
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm64
      - ppc64le
      - s390x
    flags:
      - -trimpath
    main: ./cmd/sync
    binary: nginx-asg-sync

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    vendor: NGINX Inc.
    homepage: https://github.com/nginxinc/nginx-asg-sync
    maintainer: NGINX Inc. <integrations@nginx.com>
    description: |-
      NGINX Plus Integration with Cloud Autoscaling.
      This package contains software that integrates NGINX Plus
      with AWS Auto Scaling groups and Azure Virtual Machine Scale Set
    license: BSD-2-Clause
    dependencies:
      - nginx-plus
      - systemd
    suggests:
      - logrotate
    formats:
      - deb
      - rpm
    release: 1
    section: utils
    priority: optional
    bindir: /usr/sbin
    contents:
      - src: build/config.yaml.example
        dst: /etc/nginx/config.yaml.example
        type: "config|noreplace"
      - src: build/logrotate
        dst: /etc/logrotate.d/nginx-asg-sync
        type: "config|noreplace"
      - dst: /var/log/nginx-asg-sync
        type: dir
      - src: build/nginx-asg-sync.service
        dst: /lib/systemd/system/nginx-asg-sync.service
      - src: LICENSE
        dst: /usr/share/doc/nginx-asg-sync/copyright
        packager: deb
      - src: LICENSES
        dst: /usr/share/doc/nginx-asg-sync/LICENSES
        packager: deb
      - src: LICENSE
        dst: /usr/share/licenses/nginx-asg-sync/LICENSE
        packager: rpm
      - src: LICENSES
        dst: /usr/share/licenses/nginx-asg-sync/LICENSES
        packager: rpm
      - src: README.md
        dst: /usr/share/doc/nginx-asg-sync/README
    overrides:
      rpm:
        scripts:
          postinstall: "build/postinstall.sh"
          preremove: "build/preremove.sh"
          postremove: "build/postremove.sh"

changelog:
  disable: true

archives:
  - files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - build/config.yaml.example

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

announce:
  slack:
    enabled: true
    channel: "#announcements"
    message_template: "NGINX Plus Integration with Cloud Autoscaling {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}"

milestones:
  - close: true

snapcrafts:
  - summary: NGINX Plus Integration with Cloud Autoscaling
    description: |
      This package contains software that integrates NGINX Plus
      with AWS Auto Scaling groups and Azure Virtual Machine Scale Set
    grade: stable
    confinement: strict
    publish: true
    license: BSD-2-Clause
    apps:
      nginx-asg-sync:
        command: nginx-asg-sync
        plugs: ["network", "network-bind"]
    disable: "{{ if .IsSnapshot }}true{{ end }}"

brews:
  - repository:
      owner: nginxinc
      name: homebrew-tap
      token: "{{ .Env.NGINX_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/nginxinc/nginx-asg-sync
    description: NGINX Plus Integration with Cloud Autoscaling
    license: BSD-2-Clause
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com
