#!/bin/sh

set -e

case "$1" in
    remove|purge)
      rm -rf /var/log/nginx-asg-sync
      ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
